name: freo_assignment
description: "Freo interview assignment"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.5.1
  dio: ^5.4.3+1
  easy_search_bar:
    git: https://github.com/4inka/flutter_easy_search_bar.git
  flutter_widget_from_html: ^0.14.11
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf